export const sectionData = [
  {
    id: "config",
    title: "Config",
    description: "",
    packages: [
      "nodeVersion",
      "typescript",
      "webpack",
      "react-scripts",
      "rollup",
      "vite",
      "@docusaurus/core",
    ],
  },
  {
    id: "ui",
    title: "UI",
    description: "",
    packages: ["react", "styled-components"],
  },
  {
    id: "state",
    title: "State Management",
    description: "",
    packages: ["redux", "@reduxjs/toolkit", "@tanstack/react-query"],
  },
  {
    id: "routing",
    title: "Routing",
    description: "",
    packages: ["react-router-dom"],
  },
  {
    id: "testing",
    title: "Testing",
    description: "",
    packages: ["@testing-library/react", "jest", "mocha"],
  },
  {
    id: "wallet",
    title: "Wallet",
    description: "",
    packages: [
      "@albedo-link/intent",
      "@ledgerhq/hw-app-str",
      "@ledgerhq/hw-transport-webusb",
      "@trezor/connect-plugin-stellar",
      "@trezor/connect-web",
    ],
  },
  {
    id: "stellar",
    title: "Stellar",
    description: "",
    packages: [
      "stellar-sdk",
      "stellar-base",
      "@stellar/design-system",
      "@stellar/freighter-api",
      "@stellar/frontend-helpers",
      "@stellar/eslint-config",
      "@stellar/prettier-config",
      "@stellar/tsconfig",
      "@stellar/wallet-sdk",
    ],
  },
];
